#pragma once

#include <Windows.h>

enum Key
{
	None				= 0,

	LeftMouseButton		= VK_LBUTTON,
	RightMouseButton	= VK_RBUTTON,
	MiddleMouseButton	= VK_MBUTTON,

	Backspace			= VK_BACK,
	Tab					= VK_TAB,
	Clear				= VK_CLEAR,
	Enter				= VK_RETURN,
	//Shift				= VK_SHIFT,			--- Not used, will be Left Shift or Right Shift
	//Control			= VK_CONTROL,		--- Not used, will be Left Control or Right Control
	//Alt				= VK_MENU,			--- Not used, will be Left Alt or Right Alt
	Pause				= VK_PAUSE,
	CapsLock			= VK_CAPITAL,
	Esc					= VK_ESCAPE,
	Space				= VK_SPACE,
	PageUp				= VK_PRIOR,
	PageDown			= VK_NEXT,
	End					= VK_END,
	Home				= VK_HOME,

	Left				= VK_LEFT,
	Up					= VK_UP,
	Right				= VK_RIGHT,
	Down				= VK_DOWN,

	Print				= VK_PRINT,
	PrintScreen			= VK_SNAPSHOT,
	Insert				= VK_INSERT,
	Delete				= VK_DELETE,

	Alpha0				= 0x30,
	Alpha1				= 0x31,
	Alpha2				= 0x32,
	Alpha3				= 0x33,
	Alpha4				= 0x34,
	Alpha5				= 0x35,
	Alpha6				= 0x36,
	Alpha7				= 0x37,
	Alpha8				= 0x38,
	Alpha9				= 0x39,

	A					= 0x41,
	B					= 0x42,
	C					= 0x43,
	D					= 0x44,
	E					= 0x45,
	F					= 0x46,
	G					= 0x47,
	H					= 0x48,
	I					= 0x49,
	J					= 0x4A,
	K					= 0x4B,
	L					= 0x4C,
	M					= 0x4D,
	N					= 0x4E,
	O					= 0x4F,
	P					= 0x50,
	Q					= 0x51,
	R					= 0x52,
	S					= 0x53,
	T					= 0x54,
	U					= 0x55,
	V					= 0x56,
	W					= 0x57,
	X					= 0x58,
	Y					= 0x59,
	Z					= 0x5A,

	LeftWindows			= VK_LWIN,
	RightWindows		= VK_RWIN,
	AppKey				= VK_APPS,
	Num00				= VK_NUMPAD0,
	Num01				= VK_NUMPAD1,
	Num02				= VK_NUMPAD2,
	Num03				= VK_NUMPAD3,
	Num04				= VK_NUMPAD4,
	Num05				= VK_NUMPAD5,
	Num06				= VK_NUMPAD6,
	Num07				= VK_NUMPAD7,
	Num08				= VK_NUMPAD8,
	Num09				= VK_NUMPAD9,
	NumMultiply			= VK_MULTIPLY,
	NumAdd				= VK_ADD,
	NumSeparator		= VK_SEPARATOR,
	NumSubtract			= VK_SUBTRACT,
	NumDecimal			= VK_DECIMAL,
	NumDivide			= VK_DIVIDE,

	F1					= VK_F1,
	F2					= VK_F2,
	F3					= VK_F3,
	F4					= VK_F4,
	F5					= VK_F5,
	F6					= VK_F6,
	F7					= VK_F7,
	F8					= VK_F8,
	F9					= VK_F9,
	F10					= VK_F10,
	F11					= VK_F11,
	F12					= VK_F12,
	F13					= VK_F13,
	F14					= VK_F14,
	F15					= VK_F15,
	F16					= VK_F16,
	F17					= VK_F17,
	F18					= VK_F18,
	F19					= VK_F19,
	F20					= VK_F20,
	F21					= VK_F21,
	F22					= VK_F22,
	F23					= VK_F23,
	F24					= VK_F24,

	NumLock				= VK_NUMLOCK,
	ScrollLock			= VK_SCROLL,

	LeftShift			= VK_LSHIFT,
	RightShift			= VK_RSHIFT,
	LeftControl			= VK_LCONTROL,
	RightControl		= VK_RCONTROL,
	LeftAlt				= VK_LMENU,
	RightAlt			= VK_RMENU,

	Plus				= VK_OEM_PLUS,
	Comma				= VK_OEM_COMMA,
	Minus				= VK_OEM_MINUS,
	Period				= VK_OEM_PERIOD,
	SemiColon			= VK_OEM_1,
	Slash				= VK_OEM_2,
	BackQuote			= VK_OEM_3,
	LeftBracket			= VK_OEM_4,
	BackSlash			= VK_OEM_5,
	RightBracket		= VK_OEM_6,
	SingleQuote			= VK_OEM_7,
	AngleBracket		= VK_OEM_102,
};